### ISSUE TITLE
System.InvalidOperationException on WinXP

### ISSUE THREAD

**Issue by notmmao** [sones/sones#1]
1:download http://github.com/downloads/sones/sones/sones%20GraphDB%20OSE%201.1%20binary%20Windows.zip
2:run sonesExample.exe
3:type any COMMAND
4:Unhandled Exception: System.InvalidOperationException: Could not locate Performance Counter with specified category name 'Process', counter name 'Working Set - Private'.
# 

on MSDN:http://msdn.microsoft.com/en-us/library/aa965225%28VS.85%29.aspx

Working Set - Private
#     Windows Server 2003 and Windows XP/2000:  This performance counter is not supported.

**Comment by sones** [comment]
we fixed that issue in the current checkin (23. August 2010)
