### ISSUE TITLE
Crashes in windows when try set locations

### ISSUE THREAD

**Issue by shersh** [sones/sones#2]
Hello!

I want to set location for GraphDSSharp object, but when i call CreateDatabase exception is throwing with message "IGraphFS implementation 'DiscGraphFS3' could not be activated!"

I want to save my data in hard disk and read after for working with it. Tell me please, may be i did something wrong and does any ways for doing it? 

Thanks.

Golenok Roman.
email: roman.golenok@gmail.com

**Comment by sones** [comment]
Hello!

the current trunk does not include a disk based storage implementation. We plan to release that feature soon for our open source users.
