### ISSUE TITLE
Any example of recommender systems (Empfehlungssysteme) available?

### ISSUE THREAD

**Issue by mvreg** [sones/sones#4]
Hello all 

I'm trying to write basic collaborative filtering in graph database. You have more about this on http://www.sones.com/technik-ecommerce

I have only found basic collaborative filtering query example using Gremlin on https://github.com/tinkerpop/gremlin/wiki  .
// calculate basic collaborative filtering for vertex 1
m = [:]
g.v(1).out('likes').in('likes').out('likes').groupCount(m)
m.sort{a,b -> a.value <=> b.value}

Could anyone share some similar GQL query for Sones?

Sample data format:
User(userid) -vertex
likes  (userid  likes productid) -edge
Product(productid) -vertex

**Comment by cosh** [comment]
Hello dlogar,

we are trying to give you an answer as soon as possible.

Greetings, Henning.

**Comment by cosh** [comment]
Hello dlogar,

there is more than one way to get a recommendation like this done.
1. GQL statement with a user-defined function:
   "FROM User SELECT Likes.Recommend(IsLikedBy.Likes.Name) WHERE Name = 'InterestingUserName'"
2. GQL statement without a user-defined function:
   "FROM User SELECT Likes.IsLikedBy.Likes.Name AS Recommendation, COUNT(Recommendation) AS Count
                    WHERE Name = 'InterestingUserName'
                    GROUP BY Recommendation
                    ORDER BY Count"
